### ISSUE TITLE
request for more bookmark scripts

### ISSUE THREAD

**Issue by rdrd00** [livinginpurple/FacebookMobileToDesktop#1]
can you please make bookmark script like this for redirecting www.youtube.com to m.youtube.com (reason - when i share youtube channel or user link to browser it always opens as desktop site and i want to convert it in to mobile site)

**Comment by rdrd00** [comment]
and one more very important script if possible - i want to make youtube profile picture large. i do this by manually changing "s100" to "s5000" in link like this 👇
https://yt3.googleusercontent.com/gU4o71ZnYWnTY6NxFvgWh2e7bG-kYF752ck0eANQ-uje7w9iKfFNV2oLD89wi3ZCfGHlq2xH6Lc=s100-c-k-c0x00ffffff-no-rj

so link becomes like this 👇
https://yt3.googleusercontent.com/gU4o71ZnYWnTY6NxFvgWh2e7bG-kYF752ck0eANQ-uje7w9iKfFNV2oLD89wi3ZCfGHlq2xH6Lc=s5000-c-k-c0x00ffffff-no-rj

i want a script for doing this thing for me.

I am sorry i used "create issue" feature for not raising issue but for demanding other things. i should not do this.. but please forgive me and make these bookmark scripts if possible. please!

**Comment by livinginpurple** [comment]
Script "Copy m.youtube Url.js" would copy m.youtube url.
Script "Copy s5000 Image Uri.js" would copy s5000 url.
